version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    web:
        image: httpd:2.4.46
        volumes:
            - .:/usr/local/apache2/htdocs
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        environment:
            - VIRTUAL_HOST=checkout.turbo

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./src/:/var/www
            - ~/.composer/:/root/.composer/
            - ~/.ssh:/root/.ssh # Forward local machine SSH key to docker
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=checkout"
        ports:
            - 9000:9000