name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--working-dir=src"
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          configuration: src/phpunit.xml
