name: Run tests
on: push

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('src/.env') || copy('src/.env.example', 'src/.env');"
      - run: ls src -la
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --working-dir=src
      - name: Generate key
        run: php src/artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 src/storage src/bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p src/database
          touch src/database/database.sqlite
      - name: Run Unit tests
        run: src/vendor/bin/phpunit -c src/phpunit.xml --group Unit
      - name: Run Feature tests
        run: src/vendor/bin/phpunit -c src/phpunit.xml --group Feature
      - name: Run Unit tests
        run: src/vendor/bin/phpunit -c src/phpunit.xml --group Integration
        env:
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}

